unstable_features = true

max_width = 100
hard_tabs = false
tab_spaces = 4

reorder_imports = true
group_imports = "StdExternalCrate"

struct_lit_single_line = true
fn_call_width = 70
fn_single_line = true

newline_style = "Unix"
use_small_heuristics = "Max"

control_brace_style = "AlwaysSameLine"

trailing_comma = "Never"
space_before_colon = false

# Important: do NOT touch license headers
normalize_comments = false
wrap_comments = false
